### ISSUE TITLE
Setup ‘meta’ content to include

### ISSUE THREAD

**Issue by MarcoDaniels** [MarcoDaniels/joyful-talks#3]
- [x] each page should have a `meta` object
- [x] should have support for `navigation`, `footer`, `cookie-settings`, etc
- [x] setup ports for cookie management
- [x] decode to all pages
